### ISSUE TITLE
Subtitles are not imported via YGOR

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#101]
With RDA, the representation of subtitles have changed and are not interpreted via YGOR. 

@Hornmo: Could you specifiy which Pica fields should be interpreted?

Title is in field 4000, Subtitles in field 4005. Example:
021A ƒaJournal of transportation engineeringƒhASCE, American Society of Civil Engineers, T&DI, Transportation & Development Institute
021C ƒlPart AƒaSystems

**Comment by hornmo** [comment]
@darupp I think the best solution would be to use `021Aa + ' / ' + (021Ca ?: 021Cr)` if `021C` exists, else check for `025@a`, and if neither field exists just use 021Aa.

**Comment by philboeselager** [comment]
@hornmo Is this "overruling" the specification in our wiki? ... where it is specified as follows:

- value of `variantNames` (resp. `variantNames[0]`) is appended to the value of `name`,
delimited by `': '`.

Furthermore:

- would we also write the sub title, as given by the pica+ fields from above, to `variantNames`?

**Comment by hornmo** [comment]
@philboeselager where is this specified exactly? Could you give me a link for that?

**Comment by philboeselager** [comment]
As we've agreed today, content of `025@:a` should be split into publicationTitle and publicationSubTitle, but only be used if either of the fields has not been set by other fields. Correct, @hornmo ?

Could you also please provide me with some real-world sample data here? Especially, I would need to see how title and subtitle are split in `025@:a` (if that is consistent?!).

**Comment by hornmo** [comment]
A good example would be "Physical review / D":
http://services.dnb.de/sru/zdb?version=1.1&operation=searchRetrieve&query=dnb.zdbid=1461167-3%20and%20dnb.frm=O&maximumRecords=2&recordSchema=PicaPlus-xml

In KBART: [APS-Test1.txt](https://github.com/hbz/laser-ygor/files/3841373/APS-Test1.txt)

There we have a main title (`021A:a`) = "Physical review" and in addition, there is a dedicated field for specifying the sub-series in `021C` (`l` = "D", `a` = "Particles, fields, gravitation, and cosmology"). This field can be repeated as well, so there could be another `021C`, which would describe an even narrower sub-series (in this case something like `l` = "Section 1", `a` = "Particles").

`025@:a` contains a pre-combined form of these fields: "Physical review / D", which is what we would like the `title.name` to look like in GOKb, but since this field is deprecated we should only use it if for some reason `021C:l` does not exist.

The best practice to select a finished `title.name` for GOKb would be:

If `021C` exists: `title.name` = `021A:a` + ' / ' + `021C:l` (Continue concatenating for multiple occurrences of `021C`)

else if `025@:a` exists: `title.name` = `025@:a`

else: `title.name` = `021A:a` 

This additional info is also present for titles in the title history like this:

title = `039E:Y` -> "Physical review"
sub-series = `039E:N` -> "D"
combined title = `039E:D` -> "Physical review / D"

Since `025@:a`/`039E:D` already contain a better title than `021A:a` on its own, we wouldn't have to split them up at all, BUT we would prefer to use a combination of `021A:a` + `021C:l` as `title.name` if `021C` exists.
