### ISSUE TITLE
Sending Package: Platform not included in package json

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#133]
Again a platform problem on http://phaeton-qa.hbz-nrw.de:9000/ygor/enrichment/process. 

After selecting the platform Preselect Media (https://phaeton.hbz-nrw.de/gokb/resource/show/org.gokb.cred.Platform%3A64580), you get following alert: 

    <div class="alert alert-danger" role="alert">Kein Plattform-Name vorhanden</div>
    <div class="alert alert-danger" role="alert">Keine Plattform-URL vorhanden</div>

After sending the package, you get following error: 

    ERROR, message:Package was created, but tipps have not been loaded because of validation errors!, errors:[[code:400, message:Platform is not valid!], [code:400, message:Platform is not valid!],

This is because the platform fields are left blank in the package json for each tipp:

    "platform": {
            "name": "",
            "primaryUrl": ""

As far as I see it, the platform has a correct entry and was selectable in the YGOR UI, but is somehow not processed after submitting the formular. 

[https://app.zenhub.com/files/76962941/755ab27e-eab0-4240-ad3f-316c79dbba6c/download](https://app.zenhub.com/files/76962941/755ab27e-eab0-4240-ad3f-316c79dbba6c/download)

**Comment by philboeselager** [comment]
Fixed in the data. Presumably occurred due to a line break in the platform name in the GOKb.

Probably we should create an issue for removing line breaks in GOKb data fields. This should not be done as a one-field-fix, but as a general cleanup for a multitude of fields that we have to select / specify first.

@darupp Please check if working and close this issue.
