### ISSUE TITLE
all_issns and mismatching ISSNs

### ISSUE THREAD

**Issue by philboeselager** [hbz/laser-ygor#189]
The Kbart files exported from EZB contain the column `all_issns`. This is not a Kbart standard field / column. But obviously, it occurs quite often. Hence, we could add it to our Ygor field configuration.

`all_issns` could help to resolve mismatching issns as occuring in lines 121 and 122 of https://github.com/openlibraryenvironment/gokb/files/3152744/EZB-HBZBE-01476_hbzKon_beck_2019_05_07.txt :

- the column `online_identifier` contains `2197-1609`
- the ZDB API returns `2512-3688`
- `all_issns` contains both, `2197-1609` and `2512-3688`

**Comment by philboeselager** [comment]
@darupp Would you agree to add all_issns to our config and use it to resolve mismatching ISSNs?

**Comment by darupp** [comment]
Actually I would not put any effort in this. EZB Kbart exports will not be our main import source, and how the all_issns field is filled by the EZB is somewhat cryptic. There will also be additional errors because I think all_issns is necessarily correct. After everything else works, we can re-open this ticket and have a new look at it.
