### ISSUE TITLE
E-Book Upload does not work

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#242]
Uploading e-Book-Packages (`publication_type` = _monograph_) does not work.

In the enrichment process the progress bar shows eratic behaviour (going forwards and backwards), and even after some time you don't get to the final statistics screen. 

It is not clear whether it is because there is problem with the `publication_type` or if this is because of the disabling of ZDB and EZB enrichment. 

[https://app.zenhub.com/files/76962941/a91a8569-2a55-4776-9eba-377d21104cd7/download](https://app.zenhub.com/files/76962941/a91a8569-2a55-4776-9eba-377d21104cd7/download)

**Comment by philboeselager** [comment]
Could not be reproduced for linked test file `Thieme_Ebooks_eRef_Lehrbuecher_ohnePreise_finalxlsx_1.txt` with columns repaired. I've deleted the double columns and added a column `publication_type` with value `monograph` for every entry.

Could not be reproduced for linked test file `642_75029020_Verkehrsrecht.csv` with columns repaired. I've deleted the double column `first_author`.

Tested both files on local machine and DEV.

For `utb_Gesamttitelliste_2020_KBART.tsv`, the behaviour descriped can not be reproduced either. Testing locally only. But, this file can not be processed with the current implementation. The reason is not related to `publication_type`. It is due to the KBart file's length. I guess, #227 is the issue for that behaviour.

@darupp Can you please verify that the behaviour you've described does not occur any more? If it does anyway, I assume it to be a client / browser thing. I'm using Chromium 80.

**Comment by darupp** [comment]
I tested again and could reproduce it only for the `utb_Gesamttitelliste_2020_KBART.tsv`. The bar goes very quick to 100%, stays there, drops to 0%. Tested on Chrome 80. Maybe it's really because of the file size. 

I would close this issue and prioritize #227, because the utb list with _only_ 2000 records is quite short. For #241 we would have to import title lists with >11.000 records.
