### ISSUE TITLE
Statistik: faulty titles

### ISSUE THREAD

**Issue by MiriKon** [hbz/laser-ygor#83]
Am besten sollten die Titel, die von YGOR als "faulty" bezeichnet werden, in der Statistik auch mit Namen genannt werden, damit man sofort sehen kann, um welche Titel es sich genau handelt, die als fehlerhaft entfernt werden und nicht in die GOKb eingespielt werden.

**Comment by MiriKon** [comment]
Hier ein kurzes Nachtrag: Im Upload-Tool der EZB, in dem man KBART Dateien in die Paket-Kollektionen der EZB laden kann, sieht die Rückmeldung zu den Titeln, die nicht zugeordnet werden können (in Ygor immer als "faulty" bezeichnet) ganz sinnvoll aus (s. Screenshot). Vllt könnte man es ja auch in Ygor so ähnlich einrichten, damit ganz klar ist, welche Titel im speziellen nicht in die GOKb gespielt werden. 

![ezb_upload_tool](https://user-images.githubusercontent.com/45172978/52407106-a7017c00-2acf-11e9-9d93-bf25ebd378b5.JPG)

**Comment by MiriKon** [comment]
P.S.: Im Grunde reicht hier nach Hochladen der Datei die Information aus, um welchen Titel (Name des Journals) es sich handelt, der nicht zugeordnet werden konnte. Die Angabe von Identifiern (ZDB ID, eISSN etc.) wäre auch hilfreich, wäre aber zweitrangig (und liegen teilweise auch noch gar nicht vor).

**Comment by philboeselager** [comment]
@MiriKon @hornmo Just for clarification:

- Do we (still) want invalid titles to be excluded from upload?
- Do we (still) want invalid tipps to be excluded from upload?

Alternatively, we could include invalid titles and tipps in the upload and flag them with review requests. @hornmo If we are in favour of this alternative, please send me an example of how to attach a review request to a json object.

**Comment by darupp** [comment]
The problem is that if invalid tipps are excluded from upload, the API will accept the package as correct and create it with the correct subset of tipps. So you will have an incorrect package (regarding the tipp count) that is formally correct. If you want to get it corrected, you subsequently will have to upload the whole package again, because if you upload only the invalid tipps, all other tipps will be set to retired. 

Regarding tipps, there are four cases:
Valid according to Ygor     | Valid according to GOKb API     | Consequence 
---   |   ---   | ---

**Comment by philboeselager** [comment]
OK, then the current Ygor functionality fits our requirements here. In case we need flags for invalid tipps and/or titles, please open a new issue. Closing.
