### ISSUE TITLE
Processing of KBART coverage_depth

### ISSUE THREAD

**Issue by darupp** [hbz/laser-ygor#96]
According to KBART standard, the field _coverage_notes_ can have the values _fulltext_, _selected articles_ and _abstracts_. At the moment, this field is not processed and the hard coded value _fulltext_ is inserted in the corresponding target JSON. 

This KBART field should be processed to the correct value.

**Comment by VolkerHBZ** [comment]
The value "Fulltext" that is shown in GOKB comes from the default value of property coverageDepth, whilst coverageNotes is NULL throughout the whole database, as far as I can see. Since coverageNotes has only three valid values - none of them is NULL - the correct behaviour for empty coverageNotes fields in the database has to be defined prior to a final fix of this bug.

**Comment by VolkerHBZ** [comment]
Straight forward implementation: the coverageDepth and -notes are written to the according database rows and shown in the UI correctly.
